
language: node_js
sudo: false
services:
  - postgresql
  - redis-server
before_script:
  - cp .env_sample .env
  - psql -c 'create database "apulum-graphql-api";' -U postgres
node_js:
  - "10"
install:
  - yarn
script:
  - yarn test:ci

jobs:
  include:
    - stage: Test Build
      node_js: "10"
      env:
        - NODE_ENV=production
      script: yarn start
    - stage: Produce Coverage
      node_js: "10"
      script: jest --coverage --forceExit && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
