
language: node_js
sudo: false
services:
  - postgresql
  - redis-server
before_script:
  - cp .env_sample .env
  - psql -c 'create database "apulum-graphql-api";' -U postgres
  - yarn build
node_js:
  - "10"
install:
  - yarn

jobs:
  include:
    - stage: Integration tests
      node_js: "10"
      script: yarn test:ci

    - stage: Test start
      node_js: "10"
      env:
        NODE_ENV=production
      script: yarn start

    - stage: Produce coverage
      node_js: "10"
      script: jest --coverage --forceExit && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
